name: Deploy lambda-prod

on:
  push:
    branches:
      - main # for production deployment

env:
  APP_ID: my-flea-market

  AWS_REGION: ${{ secrets.AWS_REGION }}
  # should be configured in configure-aws-credentials step
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET }}

  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  DYNAMODB_PREFIX: ${{ vars.DYNAMODB_PREFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-build
        run: npm ci

      # not yet completely prepared `testable` code
      # - name: Run tests
      #   run: npm run test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: set env
        run: |
          export ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account);
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV

      - name: testing env
        run: echo ACCOUNT_ID=${{ env.ACCOUNT_ID }}; echo "BOOM"

      - name: Run deploy-prod
        env:
          BASE_SHA: ${{ github.event.before }}
        run: |
          CREDS=`aws sts assume-role --role-arn arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.APP_ID }}-role-DeployerRole --role-session-name=gha_deployer`
          export AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
          export AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
          export AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`
          export STAGE=prod
          export SLS_DEBUG="*"
          if [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
            echo "Base SHA is all zeros, running full deploy"
            npx turbo run deploy-prod
          else
            echo "Base SHA is $BASE_SHA, running affected deploy"
            npx turbo run deploy-prod --filter=...[$BASE_SHA]
          fi
